In [ ]:
!pip install numpy pandas

In [1]:
import pandas as pd
import numpy as np
import random
import math
from copy import deepcopy
import matplotlib.pyplot as plt
from matplotlib import lines as mlines
from itertools import combinations, takewhile, product
from scipy.stats import norm, chi2, t, f
from mpl_toolkits.mplot3d import Axes3D 
from typing import List, Tuple, Dict
sqrt = math.sqrt
pd.options.display.float_format = '{:,.3f}'.format

### Linear Regression Question Type - A


In [3]:
# Data here
x = pd.read_csv('dummy.csv', dtype=float)
y = pd.read_csv('dummy2.csv', dtype=float) # Response variables
n = len(x)
r = x.columns.size

In [4]:
print ('No of samples =', len(x), '\nNo of Parameters', x.columns.size)

No of samples = 43 
No of Parameters 5


In [5]:
print('Mean Vector is:')
print(x.mean())

Mean Vector is:
1   1.070
2   1.977
3   3.047
4   3.977
5   5.372
dtype: float64


In [6]:
print('Covariance Matrix is:')
print(x.cov())

Covariance Matrix is:
       1      2      3      4      5
1  0.209 -0.070  0.140 -0.070  1.116
2 -0.070  0.023 -0.047  0.023 -0.372
3  0.140 -0.047  0.093 -0.047  0.744
4 -0.070  0.023 -0.047  0.023 -0.372
5  1.116 -0.372  0.744 -0.372  5.953


In [7]:
print('Correlation Matrix is:')
print(x.corr())

Correlation Matrix is:
       1      2      3      4      5
1  1.000 -1.000  1.000 -1.000  1.000
2 -1.000  1.000 -1.000  1.000 -1.000
3  1.000 -1.000  1.000 -1.000  1.000
4 -1.000  1.000 -1.000  1.000 -1.000
5  1.000 -1.000  1.000 -1.000  1.000


In [10]:
print ('Z Sample data is')
Z = deepcopy(x)
Z.insert(0, 'B0', 1)
print (Z)

Z Sample data is
    B0     1     2     3     4      5
0    1 1.000 2.000 3.000 4.000  5.000
1    1 1.000 2.000 3.000 4.000  5.000
2    1 1.000 2.000 3.000 4.000  5.000
3    1 1.000 2.000 3.000 4.000  5.000
4    1 1.000 2.000 3.000 4.000  5.000
5    1 1.000 2.000 3.000 4.000  5.000
6    1 1.000 2.000 3.000 4.000  5.000
7    1 1.000 2.000 3.000 4.000  5.000
8    1 1.000 2.000 3.000 4.000  5.000
9    1 1.000 2.000 3.000 4.000  5.000
10   1 1.000 2.000 3.000 4.000  5.000
11   1 1.000 2.000 3.000 4.000  5.000
12   1 1.000 2.000 3.000 4.000  5.000
13   1 1.000 2.000 3.000 4.000  5.000
14   1 1.000 2.000 3.000 4.000  5.000
15   1 1.000 2.000 3.000 4.000  5.000
16   1 1.000 2.000 3.000 4.000  5.000
17   1 1.000 2.000 3.000 4.000  5.000
18   1 1.000 2.000 3.000 4.000  5.000
19   1 1.000 2.000 3.000 4.000  5.000
20   1 1.000 2.000 3.000 4.000  5.000
21   1 1.000 2.000 3.000 4.000  5.000
22   1 1.000 2.000 3.000 4.000  5.000
23   1 1.000 2.000 3.000 4.000  5.000
24   1 1.000 2.000 3.000 4.000  5

$\hat{\beta}$ vector is

In [11]:
beta = np.linalg.pinv(Z.transpose().dot(Z)).dot(Z.transpose()).dot(y)
print(beta)

[[-0.00227551]
 [ 0.04277784]
 [-0.0195688 ]
 [ 0.02320904]
 [-0.02411982]
 [ 0.22890701]]


$\hat{y}$ vector is

In [12]:
y_exp = Z.dot(beta)
print(y_exp)

       0
0  1.119
1  1.119
2  1.119
3  1.119
4  1.119
5  1.119
6  1.119
7  1.119
8  1.119
9  1.119
10 1.119
11 1.119
12 1.119
13 1.119
14 1.119
15 1.119
16 1.119
17 1.119
18 1.119
19 1.119
20 1.119
21 1.119
22 1.119
23 1.119
24 1.119
25 1.119
26 1.119
27 1.119
28 1.119
29 1.119
30 1.119
31 1.119
32 1.119
33 5.000
34 1.119
35 1.119
36 1.119
37 1.119
38 1.119
39 1.119
40 1.119
41 1.119
42 1.119


In [13]:
print("Error Vector")
y-y_exp.to_numpy()

Error Vector


1
0  -0.119
1  -0.119
2  -0.119
3  -0.119
4  -0.119
5  -0.119
6  -0.119
7  -0.119
8  -0.119
9  -0.119
10 -0.119
11 -0.119
12 -0.119
13 -0.119
14 -0.119
15 -0.119
16 -0.119
17 -0.119
18 -0.119
19 -0.119
20 -0.119
21 -0.119
22 -0.119
23 -0.119
24 -0.119
25 -0.119
26 -0.119
27 -0.119
28 -0.119
29 -0.119
30 -0.119
31 -0.119
32 -0.119
33 -0.000
34  4.881
35 -0.119
36 -0.119
37 -0.119
38 -0.119
39 -0.119
40 -0.119
41 -0.119
42 -0.119

In [14]:
y.sum()[0]

52.0

In [25]:
epsilon = y - y_exp.to_numpy()
sse = epsilon.transpose().dot(epsilon)
print('SSE:', sse.values[0][0])
ssr = beta.transpose().dot(Z.transpose()).dot(y) - (y.sum()[0]**2)/len(y)
print('SSR:', ssr[0][0])
sst = y.transpose().dot(y) - (y.sum()[0]**2)/len(y)
print('SST:', sst.values[0][0])
rsquared = ssr/sst
rsq_adj = 1 - (ssr/(n-r-1))/(sst/(n-1))
print('Rsquared', rsquared.values[0][0])
print('Rsq_adjusted', rsq_adj.values[0][0])

SSE: 24.4047619047619
SSR: 14.71151716500556
SST: 39.116279069767444
Rsquared 0.3760970499971695
Rsq_adjusted 0.5730790243275374


In [26]:
sigma_2 = epsilon.transpose().dot(epsilon) / (n -  r - 1)
print('Sigma square for beta', sigma_2.values[0][0])

Sigma square for beta 0.6595881595881595


In [27]:
print('Covariance Matrix for beta^')
b_cov = sigma_2.values[0][0] * (Z.transpose().dot(Z))
print(b_cov)

Covariance Matrix for beta^
        B0       1       2       3       4       5
B0  28.362  30.341  56.065  86.406 112.790 152.365
1   30.341  38.256  58.044  96.300 118.726 193.919
2   56.065  58.044 111.470 169.514 223.600 290.878
3   86.406  96.300 169.514 265.814 342.326 484.797
4  112.790 118.726 223.600 342.326 449.180 595.608
5  152.365 193.919 290.878 484.797 595.608 983.446


In [28]:
print('Epsilon Covariance')


Epsilon Covariance


In [3]:
n=50
s=np.array([[2.0, 0.8], [0.8, 0.6]])
s

array([[2. , 0.8],
       [0.8, 0.6]])

In [4]:
np.linalg.eig(s)

(array([2.36301458, 0.23698542]), array([[ 0.91063291, -0.41321628],
        [ 0.41321628,  0.91063291]]))